import {readdir,readFile,writeFile,stat} from 'node:fs/promises';import {join} from 'node:path';import {gzipSync} from 'node:zlib';import {sha} from './pipeline.js';
const base='/data/civic-tech-radar/';
async function walk(dir:string):Promise<string[]>{const out:string[]=[];for(const f of await readdir(dir)){const p=join(dir,f);if((await stat(p)).isDirectory())out.push(...await walk(p));else out.push(p);}return out;}
const files=(await walk('dist')).filter(f=>!f.endsWith('release-manifest.json')).sort();
const listing=[];for(const path of files){const bytes=await readFile(path);if(['_headers','_redirects'].includes(path.split('/').at(-1)!))throw new Error('Host configuration files forbidden in artifact');if(path.endsWith('.map'))throw new Error('Source maps forbidden');if(/\.(html|js|css|json)$/.test(path)&&/\/Users\/|file:\/\/|PREVIEW_PROJECT_TOKEN|privateNotes/.test(bytes.toString()))throw new Error('Private path or key found');if(path.endsWith('.html')){const html=bytes.toString();if(/<script\b(?![^>]*\bsrc=)[^>]*>/i.test(html))throw new Error('Inline script forbidden: '+path);if(/\son\w+=/i.test(html))throw new Error('Inline handler forbidden');for(const m of html.matchAll(/(?:href|src)="([^"#]+)"/g)){const url=m[1]!;if(url.startsWith(base)){const local='dist/'+url.slice(base.length).split(/[?#]/)[0];const target=local.endsWith('/')?local+'index.html':local;await stat(target).catch(()=>{throw new Error('Broken internal URL '+url+' in '+path);});}else if(url.startsWith('/_astro/'))throw new Error('Asset missing base prefix');}}
listing.push({path:path.slice(5),sha256:sha(bytes),bytes:bytes.length});}
const html=await readFile('dist/index.html','utf8');const assets=new Set([...html.matchAll(/(?:src|href)="(\/data\/civic-tech-radar\/_astro\/[^"?]+)"/g)].map(m=>'dist/'+m[1]!.slice(base.length)));
let initial=gzipSync(html).length;for(const asset of assets)initial+=gzipSync(await readFile(asset)).length;if(initial>160*1024)throw new Error(`Initial route ${initial} bytes exceeds 160 KB gzip`);
const data=JSON.parse(await readFile('data/radar.json','utf8'));const manifest={schemaVersion:1,basePath:base,sourceRevision:data.provenance.sourceRevision,dataRevision:sha(await readFile('data/historical-input.json')),asOf:data.asOf,initialRouteGzipBytes:initial,files:listing};await writeFile('dist/release-manifest.json',JSON.stringify(manifest,null,2)+'\n');console.log(`Release: ${listing.length} files, initial route ${initial} bytes gzip; internal links, CSP script boundary and privacy scan passed.`);
